
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: obsidian-backend
    ports:
      - "7153:2112"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:2112
        # Your custom config
      - Vault__Root=/vault
      - jwt_secret=${JWT_SECRET}
      - credential__username=${USERNAME}
      - credential__password=${PASSWORD}
      
    volumes:
      # Mount the Windows vault directory to /vault in the container
      - "C:/Users/bachLH/Documents/ObsidianVault_remote:/vault"
    networks:
      - obsidian-network
    restart: unless-stopped

  frontend:
    build:
      context: ./web.frontend
      dockerfile: Dockerfile
    container_name: obsidian-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:2112/api
    depends_on:
      - backend
    networks:
      - obsidian-network
    restart: unless-stopped

networks:
  obsidian-network:
    driver: bridge

