services:
  obsidian-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: obsidian-backend
    ports:
      - "2112"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:2112
      - jwt_secret=${JWT_SECRET}
      - credential__username=${USERNAME_APP}
      - credential__password=${PASSWORD_APP}

    volumes:
      - "${VAULT_ROOT}:/vault"
    networks:
      - obsidian-network
    restart: unless-stopped

  obsidian-frontend:
    build:
      context: ./web.frontend
      dockerfile: Dockerfile
    container_name: obsidian-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - obsidian-backend
    networks:
      - obsidian-network
    restart: unless-stopped

networks:
  obsidian-network:
    driver: bridge
